[customizations.installer.kickstart]
contents = """
# Enable graphical target drive selection only
graphical

# Lock root account permanently
rootpw --lock

# Delegate user creation and localization to first boot setup wizard
firstboot --reconfig
"""