# /etc/sysctl.d/99-sourceless-security.conf

# 1. Dezactivare completă combinații de taste Magic SysRq
kernel.sysrq = 0

# 2. Ascunderea adreselor de memorie ale kernel-ului (previne exploit-uri de kernel)
kernel.kptr_restrict = 2

# 3. Restricționarea vizualizării logurilor dmesg pentru utilizatori neprivilegiați
kernel.dmesg_restrict = 1

# 4. Blocarea modificării pPointerilor BPF (Berkeley Packet Filter)
net.core.bpf_jit_harden = 2

# 5. Prevenirea pstrace-ului neautorizat pe procese existente
yama.ptrace_scope = 1