name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate ISO
        uses: blue-build/iso-action@v1
        with:
          recipe: recipes/recipe.yml
          registry_namespace: ${{ github.repository_owner }}

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sourceless-os-iso
          path: "*.iso*"
          retention-days: 7